---
- hosts: local
  connection: local
  gather_facts: False
  vars:
    instance_ids:
      - 'i-09ed5af4099b222c7'
    security_group: webservers_sg
    image: ami-035b67ea7b753ee7b 
    keypair: abcdef
    region: us-west-1
    count: 1
  vars_files:
    - krishna_aws_keys.yml

  tasks:
    - name: Stop EC2 Instance
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        group: "{{ security_group }}"
        instance_ids: '{{ instance_ids }}' 
        wait: true
        region: "{{ region }}"
        state: stopped 
      register: ec2
